version: '3.8'

services:
  slimrag-bot-duckdb:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      # Database Configuration - DuckDB
      DSN: "duckdb://./data/slimrag.db"
      
      # AI Model Configuration
      # Embedding Model
      EMBEDDING_BASE_URL: "${EMBEDDING_BASE_URL:-http://localhost:11434/v1}"
      EMBEDDING_MODEL: "${EMBEDDING_MODEL:-nomic-embed-text}"
      
      # Rerank Model (optional)
      RERANK_BASE_URL: "${RERANK_BASE_URL:-}"
      RERANK_MODEL: "${RERANK_MODEL:-}"
      
      # Assistant Model
      ASSISTANT_BASE_URL: "${ASSISTANT_BASE_URL:-http://localhost:11434/v1}"
      ASSISTANT_MODEL: "${ASSISTANT_MODEL:-llama3.2}"
      
      # OpenAI API Key (if using OpenAI models)
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      
      # Chat Bot Configuration
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN:-}"
      SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN:-}"
      SLACK_APP_TOKEN: "${SLACK_APP_TOKEN:-}"
      
      # Server Configuration
      BIND_ADDR: "0.0.0.0:8080"
      
      # Performance Configuration
      MAX_WORKERS: "${MAX_WORKERS:-3}"
      RAG_LIMIT: "${RAG_LIMIT:-10}"
      RAG_TOP_N: "${RAG_TOP_N:-5}"
      
      # Optional Chunking Configuration (overrides config file)
      CHUNK_STRATEGY: "${CHUNK_STRATEGY:-}"
      CHUNK_SIZE: "${CHUNK_SIZE:-}"
      CHUNK_OVERLAP: "${CHUNK_OVERLAP:-}"
      CHUNK_LANGUAGE: "${CHUNK_LANGUAGE:-}"
      
      # Logging
      LOG_LEVEL: "${LOG_LEVEL:-info}"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data  # Mount data directory for DuckDB
      - ./configs:/app/configs  # Mount configs for chunker configuration
    # Uncomment if you need to expose the health check port
    # ports:
    #   - "8080:8080"

volumes:
  # No postgres_data volume needed for DuckDB setup
  data:
    driver: local