version: "3"

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build ./cmd/srag

  build-linux:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build ./cmd/srag

  fmt:
    cmds:
      - go fmt ./...
      - goimports -w .
      - go mod tidy

  install-tools:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest

  ask:
    cmds:
      - go run ./cmd/srag ask "救救孩子,我怎么用 easytier 组网？"
